title: Device Config Abilities
description: Permissions for abilities pertaining to device configs.
type: object
properties:
  create:
    description: Ability to create device configs
    type: string
    enum: [not_allowed, self, self_and_all_children]
  read:
    description: Ability to read device configs
    type: string
    enum: [not_allowed, self, self_and_all_children]
  update:
    description: Ability to update device configs
    type: string
    enum: [not_allowed, self, self_and_all_children]
  delete:
    description: Ability to delete device configs
    type: string
    enum: [not_allowed, self, self_and_all_children]
